service: azure-functions-starter

provider:
  name: azure
  runtime: nodejs12
  region: ${opt:region, 'West Europe'}
  stage: ${opt:stage, 'dev'}
  apim: true
  #type: Consumption # 'Developer', 'Standard', 'Premium', 'Basic', 'Consumption'

plugins:
  - serverless-azure-functions
  - serverless-webpack

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  demoFunction:
    handler: src/handlers/demoFunction.handler
    events:
      - http: true
        x-azure-settings:
          name: req
          methods: ['get']
          authLevel: function
      - http: true
        x-azure-settings:
          name: res
          direction: out