trigger:
  branches:
    include:
      - master

variables:
  - group: sls-deploy-creds

strategy:
  matrix:
    Linux_Node14:
      imageName: "ubuntu-18.04"
      node_version: 14.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
    versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - bash: |
      npm install -g serverless
    displayName: 'Install Serverless'

  - bash: |
      # npm ci
      sls deploy --prefix gh --stage prod --region "West Europe"
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_TENANT_ID: $(AZURE_TENANT_ID)
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
      AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
    displayName: 'Deploy Azure Function App'
